<?php

namespace modava\location\models\table;

use cheatsheet\Time;
use modava\location\models\query\LocationCountryQuery;
use Yii;
use yii\db\ActiveRecord;

class LocationCountryTable extends \yii\db\ActiveRecord
{
    const STATUS_DISABLED = 0;
    const STATUS_PUBLISHED = 1;

    public static function tableName()
    {
        return 'location_country';
    }

    public static function find()
    {
        return new LocationCountryQuery(get_called_class());
    }

    public function afterDelete()
    {
        $cache = Yii::$app->cache;
        $keys = [
            'redis-get-all-country-' . $this->language,
            'redis-location-country-get-country-by-id-' . $this->id . '-' . $this->language
        ];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        $cache = Yii::$app->cache;
        $keys = [
            'redis-get-all-country-' . $this->language,
            'redis-location-country-get-country-by-id-' . $this->id . '-' . $this->language
        ];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    public static function getCountryById($id, $language = null)
    {
        $cache = Yii::$app->cache;
        $key = 'redis-location-country-get-country-by-id-' . $id . '-' . $language;
        $data = $cache->get($key);
        if ($data == false) {
            $data = self::find()->where(['id' => $id, 'language' => $language ?: Yii::$app->language])->published()->one();
            $cache->set($key, $data);
        }
        return $data;
    }

    public static function getAllCountry($language = null)
    {
        $cache = Yii::$app->cache;
        $key = 'redis-get-all-country-' . $language;

        $data = $cache->get($key);

        if ($data === false) {
            $data = self::find()->where([self::tableName() . '.language' => $language])->published()->sortDescById()->all();
            $cache->set($key, $data, Time::SECONDS_IN_A_MONTH);
        }

        return $data;
    }
}
