<?php

namespace modava\location\models\table;

use cheatsheet\Time;
use modava\location\models\query\LocationWardQuery;
use Yii;
use yii\db\ActiveRecord;

class LocationWardTable extends \yii\db\ActiveRecord
{
    const STATUS_DISABLED = 0;
    const STATUS_PUBLISHED = 1;

    public static function tableName()
    {
        return 'location_ward';
    }

    public static function find()
    {
        return new LocationWardQuery(get_called_class());
    }

    public function getDistrictHasOne()
    {
        return $this->hasOne(LocationDistrictTable::class, ['id' => 'DistrictID']);
    }

    public function afterDelete()
    {
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}
