<?php

use yii\db\Migration;

/**
 * Class m200528_024126_create_table_location_country
 */
class m200528_024126_create_table_location_country extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $tableOptions = null;
        if ($this->db->driverName === 'mysql') {
            // http://stackoverflow.com/questions/766809/whats-the-difference-between-utf8-general-ci-and-utf8-unicode-ci
            $tableOptions = 'CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE=InnoDB';
        }
        $check_country = Yii::$app->db->getTableSchema('location_country');
        if($check_country === null){
            $this->createTable('location_country', [
                'id' => $this->primaryKey(),
                'CountryCode' => $this->string(255)->null(),
                'CommonName' => $this->string(255)->null(),
                'slug' => $this->string(255)->null(),
                'FormalName' => $this->string(255)->null(),
                'CountryType' => $this->string(255)->null(),
                'CountrySubType' => $this->string(255)->null(),
                'Sovereignty' => $this->string(255)->null(),
                'Capital' => $this->string(255)->null(),
                'CurrencyCode' => $this->string(255)->null(),
                'CurrencyName' => $this->string(255)->null(),
                'TelephoneCode' => $this->string(255)->null(),
                'CountryCode3' => $this->string(255)->null(),
                'CountryNumber' => $this->string(255)->null(),
                'InternetCountryCode' => $this->string(255)->null(),
                'SortOrder' => $this->integer(11)->null(),
                'status' => $this->tinyInteger(1)->null()->defaultValue(1),
                'Flags' => $this->string(255)->null(),
                'IsDeleted' => $this->tinyInteger(1)->null()->defaultValue(0),
                'created_at' => $this->integer(11)->null(),
                'updated_at' => $this->integer(11)->null(),
                'created_by' => $this->integer(11)->null()->defaultValue(1),
                'updated_by' => $this->integer(11)->null()->defaultValue(1),
            ], $tableOptions);
            $this->addColumn('location_country', 'language', "ENUM('vi', 'en', 'jp') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'vi' COMMENT 'Language' AFTER `status`");
            $this->createIndex('index-slug', 'location_country', 'slug');
            $this->createIndex('index-language', 'location_country', 'language');
            $this->addForeignKey('fk_location_country_created_by_user', 'location_country', 'created_by', 'user', 'id', 'RESTRICT', 'CASCADE');
            $this->addForeignKey('fk_location_country_updated_by_user', 'location_country', 'updated_by', 'user', 'id', 'RESTRICT', 'CASCADE');
        }
        $check_rows = Yii::$app->db->createCommand('SELECT id FROM location_country')->queryOne();
        if($check_rows === false){
            $this->execute("INSERT INTO `location_country` (`id`, `CountryCode`, `CommonName`, `FormalName`, `CountryType`, `CountrySubType`, `Sovereignty`, `Capital`, `CurrencyCode`, `CurrencyName`, `TelephoneCode`, `CountryCode3`, `CountryNumber`, `InternetCountryCode`, `SortOrder`, `status`, `Flags`, `IsDeleted`, `created_at`, `updated_at`, `created_by`, `updated_by`) VALUES
(1, 'AC', 'Ascension', '', 'Proto Dependency', 'Dependency of Saint Helena', 'United Kingdom', 'Georgetown', 'SHP', 'Pound', '247', 'ASC', '', '.ac', 16, 0, 'ac.png', 0, NULL, 1535431504, 1, 1),
(2, 'AD', 'Andorra', 'Principality of Andorra', 'Independent State', NULL, NULL, 'Andorra la Vella', 'EUR', 'Euro', '376', 'AND', '20', '.ad', 6, 0, 'ad.png', 0, NULL, NULL, 1, 1),
(3, 'AE', 'United Arab Emirates', 'United Arab Emirates', 'Independent State', NULL, NULL, 'Abu Dhabi', 'AED', 'Dirham', '971', 'ARE', '784', '.ae', 232, 0, 'ae.png', 0, NULL, NULL, 1, 1),
(4, 'AF', 'Afghanistan', 'Islamic State of Afghanistan', 'Independent State', NULL, NULL, 'Kabul', 'AFN', 'Afghani', '93', 'AFG', '4', '.af', 2, 0, 'af.png', 0, NULL, NULL, 1, 1),
(5, 'AG', 'Antigua and Barbuda', NULL, 'Independent State', NULL, NULL, 'Saint John\'\'s', 'XCD', 'Dollar', '+1-268', 'ATG', '28', '.ag', 10, 0, 'ag.png', 0, NULL, NULL, 1, 1),
(6, 'AI', 'Anguilla', NULL, 'Dependency', 'Overseas Territory', 'United Kingdom', 'The Valley', 'XCD', 'Dollar', '+1-264', 'AIA', '660', '.ai', 8, 0, 'ai.png', 0, NULL, NULL, 1, 1),
(7, 'AL', 'Albania', 'Republic of Albania', 'Independent State', NULL, NULL, 'Tirana', 'ALL', 'Lek', '355', 'ALB', '8', '.al', 3, 0, 'al.png', 0, NULL, NULL, 1, 1),
(8, 'AM', 'Armenia', 'Republic of Armenia', 'Independent State', NULL, NULL, 'Yerevan', 'AMD', 'Dram', '374', 'ARM', '51', '.am', 12, 0, 'am.png', 0, NULL, NULL, 1, 1),
(9, 'AN', 'Netherlands Antilles', NULL, 'Proto Dependency', NULL, 'Netherlands', 'Willemstad', 'ANG', 'Guilder', '599', 'ANT', '530', '.an', 158, 0, 'an.png', 0, NULL, NULL, 1, 1),
(10, 'AO', 'Angola', 'Republic of Angola', 'Independent State', NULL, NULL, 'Luanda', 'AOA', 'Kwanza', '244', 'AGO', '24', '.ao', 7, 0, 'ao.png', 0, NULL, NULL, 1, 1),
(11, 'AQ', 'Antarctica', NULL, 'Disputed Territory', NULL, 'Undetermined', NULL, NULL, NULL, NULL, 'ATA', '10', '.aq', 9, 0, 'aq.png', 0, NULL, NULL, 1, 1),
(12, 'AR', 'Argentina', 'Argentine Republic', 'Independent State', NULL, NULL, 'Buenos Aires', 'ARS', 'Peso', '54', 'ARG', '32', '.ar', 11, 0, 'ar.png', 0, NULL, NULL, 1, 1),
(13, 'AS', 'American Samoa', 'Territory of American Samoa', 'Dependency', 'Territory', 'United States', 'Pago Pago', 'USD', 'Dollar', '+1-684', 'ASM', '16', '.as', 5, 0, 'as.png', 0, NULL, NULL, 1, 1),
(14, 'AT', 'Austria', 'Republic of Austria', 'Independent State', NULL, NULL, 'Vienna', 'EUR', 'Euro', '43', 'AUT', '40', '.at', 16, 0, 'at.png', 0, NULL, NULL, 1, 1),
(15, 'AU', 'Australia', 'Commonwealth of Australia', 'Independent State', NULL, NULL, 'Canberra', 'AUD', 'Dollar', '61', 'AUS', '36', '.au', 15, 0, 'au.png', 0, NULL, NULL, 1, 1),
(16, 'AW', 'Aruba', NULL, 'Proto Dependency', NULL, 'Netherlands', 'Oranjestad', 'AWG', 'Guilder', '297', 'ABW', '533', '.aw', 13, 0, 'aw.png', 0, NULL, NULL, 1, 1),
(17, 'AX', 'Aland', NULL, 'Proto Dependency', NULL, 'Finland', 'Mariehamn', 'EUR', 'Euro', '+358-18', 'ALA', '248', '.ax', 2, 0, 'ax.png', 0, NULL, NULL, 1, 1),
(18, 'AZ', 'Azerbaijan', 'Republic of Azerbaijan', 'Independent State', NULL, NULL, 'Baku', 'AZN', 'Manat', '994', 'AZE', '31', '.az', 17, 0, 'az.png', 0, NULL, NULL, 1, 1),
(19, 'BA', 'Bosnia and Herzegovina', NULL, 'Independent State', NULL, NULL, 'Sarajevo', 'BAM', 'Marka', '387', 'BIH', '70', '.ba', 29, 0, 'ba.png', 0, NULL, NULL, 1, 1),
(20, 'BB', 'Barbados', NULL, 'Independent State', NULL, NULL, 'Bridgetown', 'BBD', 'Dollar', '+1-246', 'BRB', '52', '.bb', 21, 0, 'bb.png', 0, NULL, NULL, 1, 1),
(21, 'BD', 'Bangladesh', 'People\'\'s Republic of Bangladesh', 'Independent State', NULL, NULL, 'Dhaka', 'BDT', 'Taka', '880', 'BGD', '50', '.bd', 20, 0, 'bd.png', 0, NULL, NULL, 1, 1),
(22, 'BE', 'Belgium', 'Kingdom of Belgium', 'Independent State', NULL, NULL, 'Brussels', 'EUR', 'Euro', '32', 'BEL', '56', '.be', 23, 0, 'be.png', 0, NULL, NULL, 1, 1),
(23, 'BF', 'Burkina Faso', NULL, 'Independent State', NULL, NULL, 'Ouagadougou', 'XOF', 'Franc', '226', 'BFA', '854', '.bf', 37, 0, 'bf.png', 0, NULL, NULL, 1, 1),
(24, 'BG', 'Bulgaria', 'Republic of Bulgaria', 'Independent State', NULL, NULL, 'Sofia', 'BGN', 'Lev', '359', 'BGR', '100', '.bg', 36, 0, 'bg.png', 0, NULL, NULL, 1, 1),
(25, 'BH', 'Bahrain', 'Kingdom of Bahrain', 'Independent State', NULL, NULL, 'Manama', 'BHD', 'Dinar', '973', 'BHR', '48', '.bh', 19, 0, 'bh.png', 0, NULL, NULL, 1, 1),
(26, 'BI', 'Burundi', 'Republic of Burundi', 'Independent State', NULL, NULL, 'Bujumbura', 'BIF', 'Franc', '257', 'BDI', '108', '.bi', 38, 0, 'bi.png', 0, NULL, NULL, 1, 1),
(27, 'BJ', 'Benin', 'Republic of Benin', 'Independent State', NULL, NULL, 'Porto-Novo', 'XOF', 'Franc', '229', 'BEN', '204', '.bj', 25, 0, 'bj.png', 0, NULL, NULL, 1, 1),
(28, 'BM', 'Bermuda', NULL, 'Dependency', 'Overseas Territory', 'United Kingdom', 'Hamilton', 'BMD', 'Dollar', '+1-441', 'BMU', '60', '.bm', 26, 0, 'bm.png', 0, NULL, NULL, 1, 1),
(29, 'BN', 'Brunei', 'Negara Brunei Darussalam', 'Independent State', NULL, NULL, 'Bandar Seri Begawan', 'BND', 'Dollar', '673', 'BRN', '96', '.bn', 35, 0, 'bn.png', 0, NULL, NULL, 1, 1),
(30, 'BO', 'Bolivia', 'Republic of Bolivia', 'Independent State', NULL, NULL, 'La Paz (administrative/legislative) and Sucre (judical)', 'BOB', 'Boliviano', '591', 'BOL', '68', '.bo', 28, 0, 'bo.png', 0, NULL, NULL, 1, 1),
(31, 'BR', 'Brazil', 'Federative Republic of Brazil', 'Independent State', NULL, NULL, 'Brasilia', 'BRL', 'Real', '55', 'BRA', '76', '.br', 32, 0, 'br.png', 0, NULL, NULL, 1, 1),
(32, 'BS', 'Bahamas, The', 'Commonwealth of The Bahamas', 'Independent State', NULL, NULL, 'Nassau', 'BSD', 'Dollar', '+1-242', 'BHS', '44', '.bs', 18, 0, 'bs.png', 0, NULL, NULL, 1, 1),
(33, 'BT', 'Bhutan', 'Kingdom of Bhutan', 'Independent State', NULL, NULL, 'Thimphu', 'BTN', 'Ngultrum', '975', 'BTN', '64', '.bt', 27, 0, 'bt.png', 0, NULL, NULL, 1, 1),
(34, 'BV', 'Bouvet Island', NULL, 'Dependency', 'Territory', 'Norway', NULL, NULL, NULL, NULL, 'BVT', '74', '.bv', 31, 0, 'bv.png', 0, NULL, NULL, 1, 1),
(35, 'BW', 'Botswana', 'Republic of Botswana', 'Independent State', NULL, NULL, 'Gaborone', 'BWP', 'Pula', '267', 'BWA', '72', '.bw', 30, 0, 'bw.png', 0, NULL, NULL, 1, 1),
(36, 'BY', 'Belarus', 'Republic of Belarus', 'Independent State', NULL, NULL, 'Minsk', 'BYR', 'Ruble', '375', 'BLR', '112', '.by', 22, 0, 'by.png', 0, NULL, NULL, 1, 1),
(37, 'BZ', 'Belize', NULL, 'Independent State', NULL, NULL, 'Belmopan', 'BZD', 'Dollar', '501', 'BLZ', '84', '.bz', 24, 0, 'bz.png', 0, NULL, NULL, 1, 1),
(38, 'CA', 'Canada', NULL, 'Independent State', NULL, NULL, 'Ottawa', 'CAD', 'Dollar', '1', 'CAN', '124', '.ca', 41, 0, 'ca.png', 0, NULL, NULL, 1, 1),
(39, 'CC', 'Cocos (Keeling) Islands', 'Territory of Cocos (Keeling) Islands', 'Dependency', 'External Territory', 'Australia', 'West Island', 'AUD', 'Dollar', '61', 'CCK', '166', '.cc', 50, 0, 'cc.png', 0, NULL, NULL, 1, 1),
(40, 'CD', 'Congo ? Kinshasa', 'Democratic Republic of the Congo', 'Independent State', NULL, NULL, 'Kinshasa', 'CDF', 'Franc', '243', 'COD', '180', '.cd', 54, 0, 'cd.png', 0, NULL, NULL, 1, 1),
(41, 'CF', 'Central African Republic', NULL, 'Independent State', NULL, NULL, 'Bangui', 'XAF', 'Franc', '236', 'CAF', '140', '.cf', 44, 0, 'cf.png', 0, NULL, NULL, 1, 1),
(42, 'CG', 'Congo ? Brazzaville', 'Republic of the Congo', 'Independent State', NULL, NULL, 'Brazzaville', 'XAF', 'Franc', '242', 'COG', '178', '.cg', 53, 0, 'cg.png', 0, NULL, NULL, 1, 1),
(43, 'CH', 'Switzerland', 'Swiss Confederation', 'Independent State', NULL, NULL, 'Bern', 'CHF', 'Franc', '41', 'CHE', '756', '.ch', 213, 0, 'ch.png', 0, NULL, NULL, 1, 1),
(44, 'CI', 'Cote d\'\'Ivoire (Ivory Coast)', 'Republic of Cote d\'\'Ivoire', 'Independent State', NULL, NULL, 'Yamoussoukro', 'XOF', 'Franc', '225', 'CIV', '384', '.ci', 57, 0, 'ci.png', 0, NULL, NULL, 1, 1),
(45, 'CK', 'Cook Islands', NULL, 'Dependency', 'Self-Governing in Free Association', 'New Zealand', 'Avarua', 'NZD', 'Dollar', '682', 'COK', '184', '.ck', 55, 0, 'ck.png', 0, NULL, NULL, 1, 1),
(46, 'CL', 'Chile', 'Republic of Chile', 'Independent State', NULL, NULL, 'Santiago (administrative/judical) and Valparaiso (legislative)', 'CLP', 'Peso', '56', 'CHL', '152', '.cl', 46, 0, 'cl.png', 0, NULL, NULL, 1, 1),
(47, 'CM', 'Cameroon', 'Republic of Cameroon', 'Independent State', NULL, NULL, 'Yaounde', 'XAF', 'Franc', '237', 'CMR', '120', '.cm', 40, 0, 'cm.png', 0, NULL, NULL, 1, 1),
(48, 'CN', 'China, People\'\'s Republic of', 'People\'\'s Republic of China', 'Independent State', NULL, NULL, 'Beijing', 'CNY', 'Yuan Renminbi', '86', 'CHN', '156', '.cn', 47, 0, 'cn.png', 0, NULL, NULL, 1, 1),
(49, 'CO', 'Colombia', 'Republic of Colombia', 'Independent State', NULL, NULL, 'Bogota', 'COP', 'Peso', '57', 'COL', '170', '.co', 51, 0, 'co.png', 0, NULL, NULL, 1, 1),
(50, 'CR', 'Costa Rica', 'Republic of Costa Rica', 'Independent State', NULL, NULL, 'San Jose', 'CRC', 'Colon', '506', 'CRI', '188', '.cr', 56, 0, 'cr.png', 0, NULL, NULL, 1, 1),
(51, 'CS', 'Kosovo', NULL, 'Disputed Territory', NULL, 'Administrated by the UN', 'Pristina', 'CSD and EUR', 'Dinar and Euro', '381', 'SCG', '891', '.cs and .yu', 119, 0, 'cs.png', 0, NULL, NULL, 1, 1),
(52, 'CU', 'Cuba', 'Republic of Cuba', 'Independent State', NULL, NULL, 'Havana', 'CUP', 'Peso', '53', 'CUB', '192', '.cu', 59, 0, 'cu.png', 0, NULL, NULL, 1, 1),
(53, 'CV', 'Cape Verde', 'Republic of Cape Verde', 'Independent State', NULL, NULL, 'Praia', 'CVE', 'Escudo', '238', 'CPV', '132', '.cv', 42, 0, 'cv.png', 0, NULL, NULL, 1, 1),
(54, 'CX', 'Christmas Island', 'Territory of Christmas Island', 'Dependency', 'External Territory', 'Australia', 'The Settlement (Flying Fish Cove)', 'AUD', 'Dollar', '61', 'CXR', '162', '.cx', 49, 0, 'cx.png', 0, NULL, NULL, 1, 1),
(55, 'CY', 'Cyprus', 'Republic of Cyprus', 'Independent State', NULL, NULL, 'Nicosia', 'CYP', 'Pound', '357', 'CYP', '196', '.cy', 60, 0, 'cy.png', 0, NULL, NULL, 1, 1),
(56, 'CZ', 'Czech Republic', NULL, 'Independent State', NULL, NULL, 'Prague', 'CZK', 'Koruna', '420', 'CZE', '203', '.cz', 61, 0, 'cz.png', 0, NULL, NULL, 1, 1),
(57, 'DE', 'Germany', 'Federal Republic of Germany', 'Independent State', NULL, NULL, 'Berlin', 'EUR', 'Euro', '49', 'DEU', '276', '.de', 84, 0, 'de.png', 0, NULL, NULL, 1, 1),
(58, 'DJ', 'Djibouti', 'Republic of Djibouti', 'Independent State', NULL, NULL, 'Djibouti', 'DJF', 'Franc', '253', 'DJI', '262', '.dj', 63, 0, 'dj.png', 0, NULL, NULL, 1, 1),
(59, 'DK', 'Denmark', 'Kingdom of Denmark', 'Independent State', NULL, NULL, 'Copenhagen', 'DKK', 'Krone', '45', 'DNK', '208', '.dk', 62, 0, 'dk.png', 0, NULL, NULL, 1, 1),
(60, 'DM', 'Dominica', 'Commonwealth of Dominica', 'Independent State', NULL, NULL, 'Roseau', 'XCD', 'Dollar', '+1-767', 'DMA', '212', '.dm', 64, 0, 'dm.png', 0, NULL, NULL, 1, 1),
(61, 'DO', 'Dominican Republic', NULL, 'Independent State', NULL, NULL, 'Santo Domingo', 'DOP', 'Peso', '+1-809 and 1-829', 'DOM', '214', '.do', 65, 0, 'do.png', 0, NULL, NULL, 1, 1),
(62, 'DZ', 'Algeria', 'People\'\'s Democratic Republic of Algeria', 'Independent State', NULL, NULL, 'Algiers', 'DZD', 'Dinar', '213', 'DZA', '12', '.dz', 4, 0, 'dz.png', 0, NULL, NULL, 1, 1),
(63, 'EC', 'Ecuador', 'Republic of Ecuador', 'Independent State', NULL, NULL, 'Quito', 'USD', 'Dollar', '593', 'ECU', '218', '.ec', 66, 0, 'ec.png', 0, NULL, NULL, 1, 1),
(64, 'EE', 'Estonia', 'Republic of Estonia', 'Independent State', NULL, NULL, 'Tallinn', 'EEK', 'Kroon', '372', 'EST', '233', '.ee', 71, 0, 'ee.png', 0, NULL, NULL, 1, 1),
(65, 'EG', 'Egypt', 'Arab Republic of Egypt', 'Independent State', NULL, NULL, 'Cairo', 'EGP', 'Pound', '20', 'EGY', '818', '.eg', 67, 0, 'eg.png', 0, NULL, NULL, 1, 1),
(66, 'EH', 'Western Sahara', NULL, 'Disputed Territory', NULL, 'Administrated by Morocco', 'El-Aaiun', 'MAD', 'Dirham', '212', 'ESH', '732', '.eh', 242, 0, 'eh.png', 0, NULL, NULL, 1, 1),
(67, 'ER', 'Eritrea', 'State of Eritrea', 'Independent State', NULL, NULL, 'Asmara', 'ERN', 'Nakfa', '291', 'ERI', '232', '.er', 70, 0, 'er.png', 0, NULL, NULL, 1, 1),
(68, 'ES', 'Spain', 'Kingdom of Spain', 'Independent State', NULL, NULL, 'Madrid', 'EUR', 'Euro', '34', 'ESP', '724', '.es', 205, 0, 'es.png', 0, NULL, NULL, 1, 1),
(69, 'ET', 'Ethiopia', 'Federal Democratic Republic of Ethiopia', 'Independent State', NULL, NULL, 'Addis Ababa', 'ETB', 'Birr', '251', 'ETH', '231', '.et', 72, 0, 'et.png', 0, NULL, NULL, 1, 1),
(70, 'FI', 'Finland', 'Republic of Finland', 'Independent State', NULL, NULL, 'Helsinki', 'EUR', 'Euro', '358', 'FIN', '246', '.fi', 76, 0, 'fi.png', 0, NULL, NULL, 1, 1),
(71, 'FJ', 'Fiji', 'Republic of the Fiji Islands', 'Independent State', NULL, NULL, 'Suva', 'FJD', 'Dollar', '679', 'FJI', '242', '.fj', 75, 0, 'fj.png', 0, NULL, NULL, 1, 1),
(72, 'FK', 'Falkland Islands', NULL, 'Dependency', 'Overseas Territory', 'United Kingdom', 'Stanley', 'FKP', 'Pound', '500', 'FLK', '238', '.fk', 73, 0, 'fk.png', 0, NULL, NULL, 1, 1),
(73, 'FM', 'Micronesia', 'Federated States of Micronesia', 'Independent State', NULL, NULL, 'Palikir', 'USD', 'Dollar', '691', 'FSM', '583', '.fm', 145, 0, 'fm.png', 0, NULL, NULL, 1, 1),
(74, 'FO', 'Faroe Islands', NULL, 'Proto Dependency', NULL, 'Denmark', 'Torshavn', 'DKK', 'Krone', '298', 'FRO', '234', '.fo', 74, 0, 'fo.png', 0, NULL, NULL, 1, 1),
(75, 'FR', 'France', 'French Republic', 'Independent State', NULL, NULL, 'Paris', 'EUR', 'Euro', '33', 'FRA', '250', '.fr', 77, 0, 'fr.png', 0, NULL, NULL, 1, 1),
(76, 'GA', 'Gabon', 'Gabonese Republic', 'Independent State', NULL, NULL, 'Libreville', 'XAF', 'Franc', '241', 'GAB', '266', '.ga', 81, 0, 'ga.png', 0, NULL, NULL, 1, 1),
(77, 'GB', 'United Kingdom', 'United Kingdom of Great Britain and Northern Ireland', 'Independent State', NULL, NULL, 'London', 'GBP', 'Pound', '44', 'GBR', '826', '.uk', 233, 0, 'gb.png', 0, NULL, NULL, 1, 1),
(78, 'GD', 'Grenada', NULL, 'Independent State', NULL, NULL, 'Saint George\'\'s', 'XCD', 'Dollar', '+1-473', 'GRD', '308', '.gd', 89, 0, 'gd.png', 0, NULL, NULL, 1, 1),
(79, 'GE', 'Georgia', 'Republic of Georgia', 'Independent State', NULL, NULL, 'Tbilisi', 'GEL', 'Lari', '995', 'GEO', '268', '.ge', 83, 0, 'ge.png', 0, NULL, NULL, 1, 1),
(80, 'GF', 'French Guiana', 'Overseas Region of Guiana', 'Proto Dependency', 'Overseas Region', 'France', 'Cayenne', 'EUR', 'Euro', '594', 'GUF', '254', '.gf', 78, 0, 'gf.png', 0, NULL, NULL, 1, 1),
(81, 'GG', 'Guernsey', 'Bailiwick of Guernsey', 'Dependency', 'Crown Dependency', 'United Kingdom', 'Saint Peter Port', 'GGP', 'Pound', '44', 'GGY', '831', '.gg', 92, 0, 'gg.png', 0, NULL, NULL, 1, 1),
(82, 'GH', 'Ghana', 'Republic of Ghana', 'Independent State', NULL, NULL, 'Accra', 'GHC', 'Cedi', '233', 'GHA', '288', '.gh', 85, 0, 'gh.png', 0, NULL, NULL, 1, 1),
(83, 'GI', 'Gibraltar', NULL, 'Dependency', 'Overseas Territory', 'United Kingdom', 'Gibraltar', 'GIP', 'Pound', '350', 'GIB', '292', '.gi', 86, 0, 'gi.png', 0, NULL, NULL, 1, 1),
(84, 'GL', 'Greenland', NULL, 'Proto Dependency', NULL, 'Denmark', 'Nuuk (Godthab)', 'DKK', 'Krone', '299', 'GRL', '304', '.gl', 88, 0, 'gl.png', 0, NULL, NULL, 1, 1),
(85, 'GM', 'Gambia, The', 'Republic of The Gambia', 'Independent State', NULL, NULL, 'Banjul', 'GMD', 'Dalasi', '220', 'GMB', '270', '.gm', 82, 0, 'gm.png', 0, NULL, NULL, 1, 1),
(86, 'GN', 'Guinea', 'Republic of Guinea', 'Independent State', NULL, NULL, 'Conakry', 'GNF', 'Franc', '224', 'GIN', '324', '.gn', 93, 0, 'gn.png', 0, NULL, NULL, 1, 1),
(87, 'GQ', 'Equatorial Guinea', 'Republic of Equatorial Guinea', 'Independent State', NULL, NULL, 'Malabo', 'XAF', 'Franc', '240', 'GNQ', '226', '.gq', 69, 0, 'gq.png', 0, NULL, NULL, 1, 1),
(88, 'GR', 'Greece', 'Hellenic Republic', 'Independent State', NULL, NULL, 'Athens', 'EUR', 'Euro', '30', 'GRC', '300', '.gr', 87, 0, 'gr.png', 0, NULL, NULL, 1, 1),
(89, 'GS', 'South Georgia Island', NULL, 'Dependency', 'Overseas Territory', 'United Kingdom', NULL, NULL, NULL, NULL, 'SGS', '239', '.gs', 204, 0, 'gs.png', 0, NULL, NULL, 1, 1),
(90, 'GT', 'Guatemala', 'Republic of Guatemala', 'Independent State', NULL, NULL, 'Guatemala', 'GTQ', 'Quetzal', '502', 'GTM', '320', '.gt', 91, 0, 'gt.png', 0, NULL, NULL, 1, 1),
(91, 'GU', 'Guam', 'Territory of Guam', 'Dependency', 'Territory', 'United States', 'Hagatna', 'USD', 'Dollar', '+1-671', 'GUM', '316', '.gu', 90, 0, 'gu.png', 0, NULL, NULL, 1, 1),
(92, 'GW', 'Guinea-Bissau', 'Republic of Guinea-Bissau', 'Independent State', NULL, NULL, 'Bissau', 'XOF', 'Franc', '245', 'GNB', '624', '.gw', 94, 0, 'gw.png', 0, NULL, NULL, 1, 1),
(93, 'GY', 'Guyana', 'Co-operative Republic of Guyana', 'Independent State', NULL, NULL, 'Georgetown', 'GYD', 'Dollar', '592', 'GUY', '328', '.gy', 95, 0, 'gy.png', 0, NULL, NULL, 1, 1),
(94, 'HK', 'Hong Kong', 'Hong Kong Special Administrative Region', 'Proto Dependency', 'Special Administrative Region', 'China', NULL, 'HKD', 'Dollar', '852', 'HKG', '344', '.hk', 99, 0, 'hk.png', 0, NULL, NULL, 1, 1),
(95, 'HM', 'Heard and McDonald Islands', 'Territory of Heard Island and McDonald Islands', 'Dependency', 'External Territory', 'Australia', NULL, NULL, NULL, NULL, 'HMD', '334', '.hm', 97, 0, 'hm.png', 0, NULL, NULL, 1, 1),
(96, 'HN', 'Honduras', 'Republic of Honduras', 'Independent State', NULL, NULL, 'Tegucigalpa', 'HNL', 'Lempira', '504', 'HND', '340', '.hn', 98, 0, 'hn.png', 0, NULL, NULL, 1, 1),
(97, 'HR', 'Croatia', 'Republic of Croatia', 'Independent State', NULL, NULL, 'Zagreb', 'HRK', 'Kuna', '385', 'HRV', '191', '.hr', 58, 0, 'hr.png', 0, NULL, NULL, 1, 1),
(98, 'HT', 'Haiti', 'Republic of Haiti', 'Independent State', NULL, NULL, 'Port-au-Prince', 'HTG', 'Gourde', '509', 'HTI', '332', '.ht', 96, 0, 'ht.png', 0, NULL, NULL, 1, 1),
(99, 'HU', 'Hungary', 'Republic of Hungary', 'Independent State', NULL, NULL, 'Budapest', 'HUF', 'Forint', '36', 'HUN', '348', '.hu', 100, 0, 'hu.png', 0, NULL, NULL, 1, 1),
(100, 'ID', 'Indonesia', 'Republic of Indonesia', 'Independent State', NULL, NULL, 'Jakarta', 'IDR', 'Rupiah', '62', 'IDN', '360', '.id', 103, 0, 'id.png', 0, NULL, NULL, 1, 1),
(101, 'IE', 'Ireland', NULL, 'Independent State', NULL, NULL, 'Dublin', 'EUR', 'Euro', '353', 'IRL', '372', '.ie', 106, 0, 'ie.png', 0, NULL, NULL, 1, 1),
(102, 'IL', 'Israel', 'State of Israel', 'Independent State', NULL, NULL, 'Jerusalem', 'ILS', 'Shekel', '972', 'ISR', '376', '.il', 108, 0, 'il.png', 0, NULL, NULL, 1, 1),
(103, 'IM', 'Isle of Man', NULL, 'Dependency', 'Crown Dependency', 'United Kingdom', 'Douglas', 'IMP', 'Pound', '44', 'IMN', '833', '.im', 107, 0, 'im.png', 0, NULL, NULL, 1, 1),
(104, 'IN', 'India', 'Republic of India', 'Independent State', NULL, NULL, 'New Delhi', 'INR', 'Rupee', '91', 'IND', '356', '.in', 102, 0, 'in.png', 0, NULL, NULL, 1, 1),
(105, 'IO', 'British Indian Ocean Territory', NULL, 'Dependency', 'Overseas Territory', 'United Kingdom', NULL, NULL, NULL, '246', 'IOT', '86', '.io', 33, 0, 'io.png', 0, NULL, NULL, 1, 1),
(106, 'IQ', 'Iraq', 'Republic of Iraq', 'Independent State', NULL, NULL, 'Baghdad', 'IQD', 'Dinar', '964', 'IRQ', '368', '.iq', 105, 0, 'iq.png', 0, NULL, NULL, 1, 1),
(107, 'IR', 'Iran', 'Islamic Republic of Iran', 'Independent State', NULL, NULL, 'Tehran', 'IRR', 'Rial', '98', 'IRN', '364', '.ir', 104, 0, 'ir.png', 0, NULL, NULL, 1, 1),
(108, 'IS', 'Iceland', 'Republic of Iceland', 'Independent State', NULL, NULL, 'Reykjavik', 'ISK', 'Krona', '354', 'ISL', '352', '.is', 101, 0, 'is.png', 0, NULL, NULL, 1, 1),
(109, 'IT', 'Italy', 'Italian Republic', 'Independent State', NULL, NULL, 'Rome', 'EUR', 'Euro', '39', 'ITA', '380', '.it', 109, 0, 'it.png', 0, NULL, NULL, 1, 1),
(110, 'JE', 'Jersey', 'Bailiwick of Jersey', 'Dependency', 'Crown Dependency', 'United Kingdom', 'Saint Helier', 'JEP', 'Pound', '44', 'JEY', '832', '.je', 112, 0, 'je.png', 0, NULL, NULL, 1, 1),
(111, 'JM', 'Jamaica', NULL, 'Independent State', NULL, NULL, 'Kingston', 'JMD', 'Dollar', '+1-876', 'JAM', '388', '.jm', 110, 0, 'jm.png', 0, NULL, NULL, 1, 1),
(112, 'JO', 'Jordan', 'Hashemite Kingdom of Jordan', 'Independent State', NULL, NULL, 'Amman', 'JOD', 'Dinar', '962', 'JOR', '400', '.jo', 113, 0, 'jo.png', 0, NULL, NULL, 1, 1),
(113, 'JP', 'Japan', NULL, 'Independent State', NULL, NULL, 'Tokyo', 'JPY', 'Yen', '81', 'JPN', '392', '.jp', 111, 0, 'jp.png', 0, NULL, NULL, 1, 1),
(114, 'KE', 'Kenya', 'Republic of Kenya', 'Independent State', NULL, NULL, 'Nairobi', 'KES', 'Shilling', '254', 'KEN', '404', '.ke', 115, 0, 'ke.png', 0, NULL, NULL, 1, 1),
(115, 'KG', 'Kyrgyzstan', 'Kyrgyz Republic', 'Independent State', NULL, NULL, 'Bishkek', 'KGS', 'Som', '996', 'KGZ', '417', '.kg', 121, 0, 'kg.png', 0, NULL, NULL, 1, 1),
(116, 'KH', 'Cambodia', 'Kingdom of Cambodia', 'Independent State', NULL, NULL, 'Phnom Penh', 'KHR', 'Riels', '855', 'KHM', '116', '.kh', 39, 0, 'kh.png', 0, NULL, NULL, 1, 1),
(117, 'KI', 'Kiribati', 'Republic of Kiribati', 'Independent State', NULL, NULL, 'Tarawa', 'AUD', 'Dollar', '686', 'KIR', '296', '.ki', 116, 0, 'ki.png', 0, NULL, NULL, 1, 1),
(118, 'KM', 'Comoros', 'Union of Comoros', 'Independent State', NULL, NULL, 'Moroni', 'KMF', 'Franc', '269', 'COM', '174', '.km', 52, 0, 'km.png', 0, NULL, NULL, 1, 1),
(119, 'KN', 'Saint Kitts and Nevis', 'Federation of Saint Kitts and Nevis', 'Independent State', NULL, NULL, 'Basseterre', 'XCD', 'Dollar', '+1-869', 'KNA', '659', '.kn', 187, 0, 'kn.png', 0, NULL, NULL, 1, 1),
(120, 'KP', 'Korea(North Korea)', 'Democratic People\'\'s Republic of Korea', 'Independent State', NULL, NULL, 'Pyongyang', 'KPW', 'Won', '850', 'PRK', '408', '.kp', 117, 0, 'kp.png', 0, NULL, NULL, 1, 1),
(121, 'KR', 'Korea(South Korea)', 'Republic of Korea', 'Independent State', NULL, NULL, 'Seoul', 'KRW', 'Won', '82', 'KOR', '410', '.kr', 118, 0, 'kr.png', 0, NULL, NULL, 1, 1),
(122, 'KW', 'Kuwait', 'State of Kuwait', 'Independent State', NULL, NULL, 'Kuwait', 'KWD', 'Dinar', '965', 'KWT', '414', '.kw', 120, 0, 'kw.png', 0, NULL, NULL, 1, 1),
(123, 'KY', 'Cayman Islands', NULL, 'Dependency', 'Overseas Territory', 'United Kingdom', 'George Town', 'KYD', 'Dollar', '+1-345', 'CYM', '136', '.ky', 43, 0, 'ky.png', 0, NULL, NULL, 1, 1),
(124, 'KZ', 'Kazakhstan', 'Republic of Kazakhstan', 'Independent State', NULL, NULL, 'Astana', 'KZT', 'Tenge', '7', 'KAZ', '398', '.kz', 114, 0, 'kz.png', 0, NULL, NULL, 1, 1),
(125, 'LA', 'Laos', 'Lao People\'\'s Democratic Republic', 'Independent State', NULL, NULL, 'Vientiane', 'LAK', 'Kip', '856', 'LAO', '418', '.la', 122, 0, 'la.png', 0, NULL, NULL, 1, 1),
(126, 'LB', 'Lebanon', 'Lebanese Republic', 'Independent State', NULL, NULL, 'Beirut', 'LBP', 'Pound', '961', 'LBN', '422', '.lb', 124, 0, 'lb.png', 0, NULL, NULL, 1, 1),
(127, 'LC', 'Saint Lucia', NULL, 'Independent State', NULL, NULL, 'Castries', 'XCD', 'Dollar', '+1-758', 'LCA', '662', '.lc', 188, 0, 'lc.png', 0, NULL, NULL, 1, 1),
(128, 'LI', 'Liechtenstein', 'Principality of Liechtenstein', 'Independent State', NULL, NULL, 'Vaduz', 'CHF', 'Franc', '423', 'LIE', '438', '.li', 128, 0, 'li.png', 0, NULL, NULL, 1, 1),
(129, 'LK', 'Sri Lanka', 'Democratic Socialist Republic of Sri Lanka', 'Independent State', NULL, NULL, 'Colombo (administrative/judical) and Sri Jayewardenepura Kotte (legislative)', 'LKR', 'Rupee', '94', 'LKA', '144', '.lk', 206, 0, 'lk.png', 0, NULL, NULL, 1, 1),
(130, 'LR', 'Liberia', 'Republic of Liberia', 'Independent State', NULL, NULL, 'Monrovia', 'LRD', 'Dollar', '231', 'LBR', '430', '.lr', 126, 0, 'lr.png', 0, NULL, NULL, 1, 1),
(131, 'LS', 'Lesotho', 'Kingdom of Lesotho', 'Independent State', NULL, NULL, 'Maseru', 'LSL', 'Loti', '266', 'LSO', '426', '.ls', 125, 0, 'ls.png', 0, NULL, NULL, 1, 1),
(132, 'LT', 'Lithuania', 'Republic of Lithuania', 'Independent State', NULL, NULL, 'Vilnius', 'LTL', 'Litas', '370', 'LTU', '440', '.lt', 129, 0, 'lt.png', 0, NULL, NULL, 1, 1),
(133, 'LU', 'Luxembourg', 'Grand Duchy of Luxembourg', 'Independent State', NULL, NULL, 'Luxembourg', 'EUR', 'Euro', '352', 'LUX', '442', '.lu', 130, 0, 'lu.png', 0, NULL, NULL, 1, 1),
(134, 'LV', 'Latvia', 'Republic of Latvia', 'Independent State', NULL, NULL, 'Riga', 'LVL', 'Lat', '371', 'LVA', '428', '.lv', 123, 0, 'lv.png', 0, NULL, NULL, 1, 1),
(135, 'LY', 'Libya', 'Great Socialist People\'\'s Libyan Arab Jamahiriya', 'Independent State', NULL, NULL, 'Tripoli', 'LYD', 'Dinar', '218', 'LBY', '434', '.ly', 127, 0, 'ly.png', 0, NULL, NULL, 1, 1),
(136, 'MA', 'Morocco', 'Kingdom of Morocco', 'Independent State', NULL, NULL, 'Rabat', 'MAD', 'Dirham', '212', 'MAR', '504', '.ma', 151, 0, 'ma.png', 0, NULL, NULL, 1, 1),
(137, 'MC', 'Monaco', 'Principality of Monaco', 'Independent State', NULL, NULL, 'Monaco', 'EUR', 'Euro', '377', 'MCO', '492', '.mc', 147, 0, 'mc.png', 0, NULL, NULL, 1, 1),
(138, 'MD', 'Moldova', 'Republic of Moldova', 'Independent State', NULL, NULL, 'Chisinau', 'MDL', 'Leu', '373', 'MDA', '498', '.md', 146, 0, 'md.png', 0, NULL, NULL, 1, 1),
(139, 'ME', 'Montenegro', 'Republic of Montenegro', 'Independent State', NULL, NULL, 'Podgorica', 'EUR', 'Euro', '382', 'MNE', '499', '.me and .yu', 149, 0, 'me.png', 0, NULL, NULL, 1, 1),
(140, 'MG', 'Madagascar', 'Republic of Madagascar', 'Independent State', NULL, NULL, 'Antananarivo', 'MGA', 'Ariary', '261', 'MDG', '450', '.mg', 133, 0, 'mg.png', 0, NULL, NULL, 1, 1),
(141, 'MH', 'Marshall Islands', 'Republic of the Marshall Islands', 'Independent State', NULL, NULL, 'Majuro', 'USD', 'Dollar', '692', 'MHL', '584', '.mh', 139, 0, 'mh.png', 0, NULL, NULL, 1, 1),
(142, 'MK', 'Macedonia', 'Republic of Macedonia', 'Independent State', NULL, NULL, 'Skopje', 'MKD', 'Denar', '389', 'MKD', '807', '.mk', 132, 0, 'mk.png', 0, NULL, NULL, 1, 1),
(143, 'ML', 'Mali', 'Republic of Mali', 'Independent State', NULL, NULL, 'Bamako', 'XOF', 'Franc', '223', 'MLI', '466', '.ml', 137, 0, 'ml.png', 0, NULL, NULL, 1, 1),
(144, 'MM', 'Myanmar (Burma)', 'Union of Myanmar', 'Independent State', NULL, NULL, 'Naypyidaw', 'MMK', 'Kyat', '95', 'MMR', '104', '.mm', 153, 0, 'mm.png', 0, NULL, NULL, 1, 1),
(145, 'MN', 'Mongolia', NULL, 'Independent State', NULL, NULL, 'Ulaanbaatar', 'MNT', 'Tugrik', '976', 'MNG', '496', '.mn', 148, 0, 'mn.png', 0, NULL, NULL, 1, 1),
(146, 'MO', 'Macau', 'Macau Special Administrative Region', 'Proto Dependency', 'Special Administrative Region', 'China', 'Macau', 'MOP', 'Pataca', '853', 'MAC', '446', '.mo', 131, 0, 'mo.png', 0, NULL, NULL, 1, 1),
(147, 'MP', 'Northern Mariana Islands', 'Commonwealth of The Northern Mariana Islands', 'Dependency', 'Commonwealth', 'United States', 'Saipan', 'USD', 'Dollar', '+1-670', 'MNP', '580', '.mp', 166, 0, 'mp.png', 0, NULL, NULL, 1, 1),
(148, 'MQ', 'Martinique', 'Overseas Region of Martinique', 'Proto Dependency', 'Overseas Region', 'France', 'Fort-de-France', 'EUR', 'Euro', '596', 'MTQ', '474', '.mq', 140, 0, 'mq.png', 0, NULL, NULL, 1, 1),
(149, 'MR', 'Mauritania', 'Islamic Republic of Mauritania', 'Independent State', NULL, NULL, 'Nouakchott', 'MRO', 'Ouguiya', '222', 'MRT', '478', '.mr', 141, 0, 'mr.png', 0, NULL, NULL, 1, 1),
(150, 'MS', 'Montserrat', NULL, 'Dependency', 'Overseas Territory', 'United Kingdom', 'Plymouth', 'XCD', 'Dollar', '+1-664', 'MSR', '500', '.ms', 150, 0, 'ms.png', 0, NULL, NULL, 1, 1),
(151, 'MT', 'Malta', 'Republic of Malta', 'Independent State', NULL, NULL, 'Valletta', 'MTL', 'Lira', '356', 'MLT', '470', '.mt', 138, 0, 'mt.png', 0, NULL, NULL, 1, 1),
(152, 'MU', 'Mauritius', 'Republic of Mauritius', 'Independent State', NULL, NULL, 'Port Louis', 'MUR', 'Rupee', '230', 'MUS', '480', '.mu', 142, 0, 'mu.png', 0, NULL, NULL, 1, 1),
(153, 'MV', 'Maldives', 'Republic of Maldives', 'Independent State', NULL, NULL, 'Male', 'MVR', 'Rufiyaa', '960', 'MDV', '462', '.mv', 136, 0, 'mv.png', 0, NULL, NULL, 1, 1),
(154, 'MW', 'Malawi', 'Republic of Malawi', 'Independent State', NULL, NULL, 'Lilongwe', 'MWK', 'Kwacha', '265', 'MWI', '454', '.mw', 134, 0, 'mw.png', 0, NULL, NULL, 1, 1),
(155, 'MX', 'Mexico', 'United Mexican States', 'Independent State', NULL, NULL, 'Mexico', 'MXN', 'Peso', '52', 'MEX', '484', '.mx', 144, 0, 'mx.png', 0, NULL, NULL, 1, 1),
(156, 'MY', 'Malaysia', NULL, 'Independent State', NULL, NULL, 'Kuala Lumpur (legislative/judical) and Putrajaya (administrative)', 'MYR', 'Ringgit', '60', 'MYS', '458', '.my', 135, 0, 'my.png', 0, NULL, NULL, 1, 1),
(157, 'MZ', 'Mozambique', 'Republic of Mozambique', 'Independent State', NULL, NULL, 'Maputo', 'MZM', 'Meticail', '258', 'MOZ', '508', '.mz', 152, 0, 'mz.png', 0, NULL, NULL, 1, 1),
(158, 'NA', 'Namibia', 'Republic of Namibia', 'Independent State', NULL, NULL, 'Windhoek', 'NAD', 'Dollar', '264', 'NAM', '516', '.na', 154, 0, 'na.png', 0, NULL, NULL, 1, 1),
(159, 'NC', 'New Caledonia', NULL, 'Dependency', 'Sui generis Collectivity', 'France', 'Noumea', 'XPF', 'Franc', '687', 'NCL', '540', '.nc', 159, 0, 'nc.png', 0, NULL, NULL, 1, 1),
(160, 'NE', 'Niger', 'Republic of Niger', 'Independent State', NULL, NULL, 'Niamey', 'XOF', 'Franc', '227', 'NER', '562', '.ne', 162, 0, 'ne.png', 0, NULL, NULL, 1, 1),
(161, 'NF', 'Norfolk Island', 'Territory of Norfolk Island', 'Dependency', 'External Territory', 'Australia', 'Kingston', 'AUD', 'Dollar', '672', 'NFK', '574', '.nf', 165, 0, 'nf.png', 0, NULL, NULL, 1, 1),
(162, 'NG', 'Nigeria', 'Federal Republic of Nigeria', 'Independent State', NULL, NULL, 'Abuja', 'NGN', 'Naira', '234', 'NGA', '566', '.ng', 163, 0, 'ng.png', 0, NULL, NULL, 1, 1),
(163, 'NI', 'Nicaragua', 'Republic of Nicaragua', 'Independent State', NULL, NULL, 'Managua', 'NIO', 'Cordoba', '505', 'NIC', '558', '.ni', 161, 0, 'ni.png', 0, NULL, NULL, 1, 1),
(164, 'NL', 'Netherlands', 'Kingdom of the Netherlands', 'Independent State', NULL, NULL, 'Amsterdam (administrative) and The Hague (legislative/judical)', 'EUR', 'Euro', '31', 'NLD', '528', '.nl', 157, 0, 'nl.png', 0, NULL, NULL, 1, 1),
(165, 'NO', 'Norway', 'Kingdom of Norway', 'Independent State', NULL, NULL, 'Oslo', 'NOK', 'Krone', '47', 'NOR', '578', '.no', 167, 0, 'no.png', 0, NULL, NULL, 1, 1),
(166, 'NP', 'Nepal', NULL, 'Independent State', NULL, NULL, 'Kathmandu', 'NPR', 'Rupee', '977', 'NPL', '524', '.np', 156, 0, 'np.png', 0, NULL, NULL, 1, 1),
(167, 'NR', 'Nauru', 'Republic of Nauru', 'Independent State', NULL, NULL, 'Yaren', 'AUD', 'Dollar', '674', 'NRU', '520', '.nr', 155, 0, 'nr.png', 0, NULL, NULL, 1, 1),
(168, 'NU', 'Niue', NULL, 'Dependency', 'Self-Governing in Free Association', 'New Zealand', 'Alofi', 'NZD', 'Dollar', '683', 'NIU', '570', '.nu', 164, 0, 'nu.png', 0, NULL, NULL, 1, 1),
(169, 'NZ', 'New Zealand', NULL, 'Independent State', NULL, NULL, 'Wellington', 'NZD', 'Dollar', '64', 'NZL', '554', '.nz', 160, 0, 'nz.png', 0, NULL, NULL, 1, 1),
(170, 'OM', 'Oman', 'Sultanate of Oman', 'Independent State', NULL, NULL, 'Muscat', 'OMR', 'Rial', '968', 'OMN', '512', '.om', 168, 0, 'om.png', 0, NULL, NULL, 1, 1),
(171, 'PA', 'Panama', 'Republic of Panama', 'Independent State', NULL, NULL, 'Panama', 'PAB', 'Balboa', '507', 'PAN', '591', '.pa', 172, 0, 'pa.png', 0, NULL, NULL, 1, 1),
(172, 'PE', 'Peru', 'Republic of Peru', 'Independent State', NULL, NULL, 'Lima', 'PEN', 'Sol', '51', 'PER', '604', '.pe', 175, 0, 'pe.png', 0, NULL, NULL, 1, 1),
(173, 'PF', 'French Polynesia', 'Overseas Country of French Polynesia', 'Dependency', 'Overseas Collectivity', 'France', 'Papeete', 'XPF', 'Franc', '689', 'PYF', '258', '.pf', 79, 0, 'pf.png', 0, NULL, NULL, 1, 1),
(174, 'PG', 'Papua New Guinea', 'Independent State of Papua New Guinea', 'Independent State', NULL, NULL, 'Port Moresby', 'PGK', 'Kina', '675', 'PNG', '598', '.pg', 173, 0, 'pg.png', 0, NULL, NULL, 1, 1),
(175, 'PH', 'Philippines', 'Republic of the Philippines', 'Independent State', NULL, NULL, 'Manila', 'PHP', 'Peso', '63', 'PHL', '608', '.ph', 176, 0, 'ph.png', 0, NULL, NULL, 1, 1),
(176, 'PK', 'Pakistan', 'Islamic Republic of Pakistan', 'Independent State', NULL, NULL, 'Islamabad', 'PKR', 'Rupee', '92', 'PAK', '586', '.pk', 169, 0, 'pk.png', 0, NULL, NULL, 1, 1),
(177, 'PL', 'Poland', 'Republic of Poland', 'Independent State', NULL, NULL, 'Warsaw', 'PLN', 'Zloty', '48', 'POL', '616', '.pl', 178, 0, 'pl.png', 0, NULL, NULL, 1, 1),
(178, 'PM', 'Saint Pierre and Miquelon', 'Territorial Collectivity of Saint Pierre and Miquelon', 'Dependency', 'Overseas Collectivity', 'France', 'Saint-Pierre', 'EUR', 'Euro', '508', 'SPM', '666', '.pm', 189, 0, 'pm.png', 0, NULL, NULL, 1, 1),
(179, 'PN', 'Pitcairn Islands', NULL, 'Dependency', 'Overseas Territory', 'United Kingdom', 'Adamstown', 'NZD', 'Dollar', NULL, 'PCN', '612', '.pn', 177, 0, 'pn.png', 0, NULL, NULL, 1, 1),
(180, 'PR', 'Puerto Rico', 'Commonwealth of Puerto Rico', 'Dependency', 'Commonwealth', 'United States', 'San Juan', 'USD', 'Dollar', '+1-787 and 1-939', 'PRI', '630', '.pr', 180, 0, 'pr.png', 0, NULL, NULL, 1, 1),
(181, 'PS', 'Palestinian Territories', NULL, 'Disputed Territory', NULL, 'Administrated by Israel', 'Gaza City (Gaza Strip) and Ramallah (West Bank)', 'ILS', 'Shekel', '970', 'PSE', '275', '.ps', 171, 0, 'ps.png', 0, NULL, NULL, 1, 1),
(182, 'PT', 'Portugal', 'Portuguese Republic', 'Independent State', NULL, NULL, 'Lisbon', 'EUR', 'Euro', '351', 'PRT', '620', '.pt', 179, 0, 'pt.png', 0, NULL, NULL, 1, 1),
(183, 'PW', 'Palau', 'Republic of Palau', 'Independent State', NULL, NULL, 'Melekeok', 'USD', 'Dollar', '680', 'PLW', '585', '.pw', 170, 0, 'pw.png', 0, NULL, NULL, 1, 1),
(184, 'PY', 'Paraguay', 'Republic of Paraguay', 'Independent State', NULL, NULL, 'Asuncion', 'PYG', 'Guarani', '595', 'PRY', '600', '.py', 174, 0, 'py.png', 0, NULL, NULL, 1, 1),
(185, 'QA', 'Qatar', 'State of Qatar', 'Independent State', NULL, NULL, 'Doha', 'QAR', 'Rial', '974', 'QAT', '634', '.qa', 181, 0, 'qa.png', 0, NULL, NULL, 1, 1),
(186, 'RE', 'Reunion', 'Overseas Region of Reunion', 'Proto Dependency', 'Overseas Region', 'France', 'Saint-Denis', 'EUR', 'Euro', '262', 'REU', '638', '.re', 182, 0, 're.png', 0, NULL, NULL, 1, 1),
(187, 'RO', 'Romania', NULL, 'Independent State', NULL, NULL, 'Bucharest', 'RON', 'Leu', '40', 'ROU', '642', '.ro', 183, 0, 'ro.png', 0, NULL, NULL, 1, 1),
(188, 'RS', 'Serbia', 'Republic of Serbia', 'Independent State', NULL, NULL, 'Belgrade', 'RSD', 'Dinar', '381', 'SRB', '688', '.rs and .yu', 195, 0, 'rs.png', 0, NULL, NULL, 1, 1),
(189, 'RU', 'Russia', 'Russian Federation', 'Independent State', NULL, NULL, 'Moscow', 'RUB', 'Ruble', '7', 'RUS', '643', '.ru and .su', 184, 0, 'ru.png', 0, NULL, NULL, 1, 1),
(190, 'RW', 'Rwanda', 'Republic of Rwanda', 'Independent State', NULL, NULL, 'Kigali', 'RWF', 'Franc', '250', 'RWA', '646', '.rw', 185, 0, 'rw.png', 0, NULL, NULL, 1, 1),
(191, 'SA', 'Saudi Arabia', 'Kingdom of Saudi Arabia', 'Independent State', NULL, NULL, 'Riyadh', 'SAR', 'Rial', '966', 'SAU', '682', '.sa', 193, 0, 'sa.png', 0, NULL, NULL, 1, 1),
(192, 'SB', 'Solomon Islands', NULL, 'Independent State', NULL, NULL, 'Honiara', 'SBD', 'Dollar', '677', 'SLB', '90', '.sb', 201, 0, 'sb.png', 0, NULL, NULL, 1, 1),
(193, 'SC', 'Seychelles', 'Republic of Seychelles', 'Independent State', NULL, NULL, 'Victoria', 'SCR', 'Rupee', '248', 'SYC', '690', '.sc', 196, 0, 'sc.png', 0, NULL, NULL, 1, 1),
(194, 'SD', 'Sudan', 'Republic of the Sudan', 'Independent State', NULL, NULL, 'Khartoum', 'SDD', 'Dinar', '249', 'SDN', '736', '.sd', 208, 0, 'sd.png', 0, NULL, NULL, 1, 1),
(195, 'SE', 'Sweden', 'Kingdom of Sweden', 'Independent State', NULL, NULL, 'Stockholm', 'SEK', 'Kronoa', '46', 'SWE', '752', '.se', 212, 0, 'se.png', 0, NULL, NULL, 1, 1),
(196, 'SG', 'Singapore', 'Republic of Singapore', 'Independent State', NULL, NULL, 'Singapore', 'SGD', 'Dollar', '65', 'SGP', '702', '.sg', 198, 0, 'sg.png', 0, NULL, NULL, 1, 1),
(197, 'SH', 'Saint Helena', NULL, 'Dependency', 'Overseas Territory', 'United Kingdom', 'Jamestown', 'SHP', 'Pound', '290', 'SHN', '654', '.sh', 186, 0, 'sh.png', 0, NULL, NULL, 1, 1),
(198, 'SI', 'Slovenia', 'Republic of Slovenia', 'Independent State', NULL, NULL, 'Ljubljana', 'EUR', 'Euro', '386', 'SVN', '705', '.si', 200, 0, 'si.png', 0, NULL, NULL, 1, 1),
(199, 'SJ', 'Svalbard', NULL, 'Proto Dependency', NULL, 'Norway', 'Longyearbyen', 'NOK', 'Krone', '47', 'SJM', '744', '.sj', 210, 0, 'sj.png', 0, NULL, NULL, 1, 1),
(200, 'SK', 'Slovakia', 'Slovak Republic', 'Independent State', NULL, NULL, 'Bratislava', 'SKK', 'Koruna', '421', 'SVK', '703', '.sk', 199, 0, 'sk.png', 0, NULL, NULL, 1, 1),
(201, 'SL', 'Sierra Leone', 'Republic of Sierra Leone', 'Independent State', NULL, NULL, 'Freetown', 'SLL', 'Leone', '232', 'SLE', '694', '.sl', 197, 0, 'sl.png', 0, NULL, NULL, 1, 1),
(202, 'SM', 'San Marino', 'Republic of San Marino', 'Independent State', NULL, NULL, 'San Marino', 'EUR', 'Euro', '378', 'SMR', '674', '.sm', 191, 0, 'sm.png', 0, NULL, NULL, 1, 1),
(203, 'SN', 'Senegal', 'Republic of Senegal', 'Independent State', NULL, NULL, 'Dakar', 'XOF', 'Franc', '221', 'SEN', '686', '.sn', 194, 0, 'sn.png', 0, NULL, NULL, 1, 1),
(204, 'SO', 'Somalia', NULL, 'Independent State', NULL, NULL, 'Mogadishu', 'SOS', 'Shilling', '252', 'SOM', '706', '.so', 202, 0, 'so.png', 0, NULL, NULL, 1, 1),
(205, 'SR', 'Suriname', 'Republic of Suriname', 'Independent State', NULL, NULL, 'Paramaribo', 'SRD', 'Dollar', '597', 'SUR', '740', '.sr', 209, 0, 'sr.png', 0, NULL, NULL, 1, 1),
(206, 'ST', 'Sao Tome and Principe', 'Democratic Republic of Sao Tome and Principe', 'Independent State', NULL, NULL, 'Sao Tome', 'STD', 'Dobra', '239', 'STP', '678', '.st', 192, 0, 'st.png', 0, NULL, NULL, 1, 1),
(207, 'SV', 'El Salvador', 'Republic of El Salvador', 'Independent State', NULL, NULL, 'San Salvador', 'USD', 'Dollar', '503', 'SLV', '222', '.sv', 68, 0, 'sv.png', 0, NULL, NULL, 1, 1),
(208, 'SY', 'Syria', 'Syrian Arab Republic', 'Independent State', NULL, NULL, 'Damascus', 'SYP', 'Pound', '963', 'SYR', '760', '.sy', 214, 0, 'sy.png', 0, NULL, NULL, 1, 1),
(209, 'SZ', 'Swaziland', 'Kingdom of Swaziland', 'Independent State', NULL, NULL, 'Mbabane (administrative) and Lobamba (legislative)', 'SZL', 'Lilangeni', '268', 'SWZ', '748', '.sz', 211, 0, 'sz.png', 0, NULL, NULL, 1, 1),
(210, 'TA', 'Tristan da Cunha', NULL, 'Proto Dependency', 'Dependency of Saint Helena', 'United Kingdom', 'Edinburgh', 'SHP', 'Pound', '290', 'TAA', NULL, NULL, 223, 0, 'ta.png', 0, NULL, NULL, 1, 1),
(211, 'TC', 'Turks and Caicos Islands', NULL, 'Dependency', 'Overseas Territory', 'United Kingdom', 'Grand Turk', 'USD', 'Dollar', '+1-649', 'TCA', '796', '.tc', 227, 0, 'tc.png', 0, NULL, NULL, 1, 1),
(212, 'TD', 'Chad', 'Republic of Chad', 'Independent State', NULL, NULL, 'N\"Djamena', 'XAF', 'Franc', '235', 'TCD', '148', '.td', 45, 0, 'td.png', 0, NULL, NULL, 1, 1),
(213, 'TF', 'French Southern Territories', 'Territory of the French Southern and Antarctic Lands', 'Dependency', 'Overseas Territory', 'France', 'Martin-de-Vivi?s', NULL, NULL, NULL, 'ATF', '260', '.tf', 80, 0, 'tf.png', 0, NULL, NULL, 1, 1),
(214, 'TG', 'Togo', 'Togolese Republic', 'Independent State', NULL, NULL, 'Lome', 'XOF', 'Franc', '228', 'TGO', '768', '.tg', 219, 0, 'tg.png', 0, NULL, NULL, 1, 1),
(215, 'TH', 'Thailand', 'Kingdom of Thailand', 'Independent State', NULL, NULL, 'Bangkok', 'THB', 'Baht', '66', 'THA', '764', '.th', 217, 0, 'th.png', 0, NULL, NULL, 1, 1),
(216, 'TJ', 'Tajikistan', 'Republic of Tajikistan', 'Independent State', NULL, NULL, 'Dushanbe', 'TJS', 'Somoni', '992', 'TJK', '762', '.tj', 215, 0, 'tj.png', 0, NULL, NULL, 1, 1),
(217, 'TK', 'Tokelau', NULL, 'Dependency', 'Territory', 'New Zealand', NULL, 'NZD', 'Dollar', '690', 'TKL', '772', '.tk', 220, 0, 'tk.png', 0, NULL, NULL, 1, 1),
(218, 'TL', 'Timor-Leste (East Timor)', 'Democratic Republic of Timor-Leste', 'Independent State', NULL, NULL, 'Dili', 'USD', 'Dollar', '670', 'TLS', '626', '.tp and .tl', 218, 0, 'tl.png', 0, NULL, NULL, 1, 1),
(219, 'TM', 'Turkmenistan', NULL, 'Independent State', NULL, NULL, 'Ashgabat', 'TMM', 'Manat', '993', 'TKM', '795', '.tm', 226, 0, 'tm.png', 0, NULL, NULL, 1, 1),
(220, 'TN', 'Tunisia', 'Tunisian Republic', 'Independent State', NULL, NULL, 'Tunis', 'TND', 'Dinar', '216', 'TUN', '788', '.tn', 224, 0, 'tn.png', 0, NULL, NULL, 1, 1),
(221, 'TO', 'Tonga', 'Kingdom of Tonga', 'Independent State', NULL, NULL, 'Nuku\"alofa', 'TOP', 'Pa\"anga', '676', 'TON', '776', '.to', 221, 0, 'to.png', 0, NULL, NULL, 1, 1),
(222, 'TR', 'Turkey', 'Republic of Turkey', 'Independent State', NULL, NULL, 'Ankara', 'TRY', 'Lira', '90', 'TUR', '792', '.tr', 225, 0, 'tr.png', 0, NULL, NULL, 1, 1),
(223, 'TT', 'Trinidad and Tobago', 'Republic of Trinidad and Tobago', 'Independent State', NULL, NULL, 'Port-of-Spain', 'TTD', 'Dollar', '+1-868', 'TTO', '780', '.tt', 222, 0, 'tt.png', 0, NULL, NULL, 1, 1),
(224, 'TV', 'Tuvalu', NULL, 'Independent State', NULL, NULL, 'Funafuti', 'AUD', 'Dollar', '688', 'TUV', '798', '.tv', 228, 0, 'tv.png', 0, NULL, NULL, 1, 1),
(225, 'TW', 'China, Republic of (Taiwan)', 'Republic of China', 'Proto Independent State', NULL, NULL, 'Taipei', 'TWD', 'Dollar', '886', 'TWN', '158', '.tw', 48, 0, 'tw.png', 0, NULL, NULL, 1, 1),
(226, 'TZ', 'Tanzania', 'United Republic of Tanzania', 'Independent State', NULL, NULL, 'Dar es Salaam (administrative/judical) and Dodoma (legislative)', 'TZS', 'Shilling', '255', 'TZA', '834', '.tz', 216, 0, 'tz.png', 0, NULL, NULL, 1, 1),
(227, 'UA', 'Ukraine', NULL, 'Independent State', NULL, NULL, 'Kiev', 'UAH', 'Hryvnia', '380', 'UKR', '804', '.ua', 231, 0, 'ua.png', 0, NULL, NULL, 1, 1),
(228, 'UG', 'Uganda', 'Republic of Uganda', 'Independent State', NULL, NULL, 'Kampala', 'UGX', 'Shilling', '256', 'UGA', '800', '.ug', 230, 0, 'ug.png', 0, NULL, NULL, 1, 1),
(229, 'US', 'United States', 'United States of America', 'Independent State', NULL, NULL, 'Washington', 'USD', 'Dollar', '1', 'USA', '840', '.us', 234, 0, 'us.png', 0, NULL, NULL, 1, 1),
(230, 'UY', 'Uruguay', 'Oriental Republic of Uruguay', 'Independent State', NULL, NULL, 'Montevideo', 'UYU', 'Peso', '598', 'URY', '858', '.uy', 235, 0, 'uy.png', 0, NULL, NULL, 1, 1),
(231, 'UZ', 'Uzbekistan', 'Republic of Uzbekistan', 'Independent State', NULL, NULL, 'Tashkent', 'UZS', 'Som', '998', 'UZB', '860', '.uz', 236, 0, 'uz.png', 0, NULL, NULL, 1, 1),
(232, 'VA', 'Vatican City', 'State of the Vatican City', 'Independent State', NULL, NULL, 'Vatican City', 'EUR', 'Euro', '379', 'VAT', '336', '.va', 238, 0, 'va.png', 0, NULL, NULL, 1, 1),
(233, 'VC', 'St. Vincent and the Grenadines', NULL, 'Independent State', NULL, NULL, 'Kingstown', 'XCD', 'Dollar', '+1-784', 'VCT', '670', '.vc', 207, 0, 'vc.png', 0, NULL, NULL, 1, 1),
(234, 'VE', 'Venezuela', 'Bolivarian Republic of Venezuela', 'Independent State', NULL, NULL, 'Caracas', 'VEB', 'Bolivar', '58', 'VEN', '862', '.ve', 239, 0, 've.png', 0, NULL, NULL, 1, 1),
(235, 'VG', 'British Virgin Islands', NULL, 'Dependency', 'Overseas Territory', 'United Kingdom', 'Road Town', 'USD', 'Dollar', '+1-284', 'VGB', '92', '.vg', 34, 0, 'vg.png', 0, NULL, NULL, 1, 1),
(236, 'VI', 'U.S. Virgin Islands', 'United States Virgin Islands', 'Dependency', 'Territory', 'United States', 'Charlotte Amalie', 'USD', 'Dollar', '+1-340', 'VIR', '850', '.vi', 229, 0, 'vi.png', 0, NULL, NULL, 1, 1),
(237, 'VN', 'Việt Nam', 'Socialist Republic of Vietnam', 'Independent State', '', '', 'Hanoi', 'VND', 'Dong', '84', 'VNM', '704', '.vn', 1, 1, 'vn.png', 0, NULL, NULL, 1, 1),
(238, 'VU', 'Vanuatu', 'Republic of Vanuatu', 'Independent State', NULL, NULL, 'Port-Vila', 'VUV', 'Vatu', '678', 'VUT', '548', '.vu', 237, 0, 'vu.png', 0, NULL, NULL, 1, 1),
(239, 'WF', 'Wallis and Futuna', 'Collectivity of the Wallis and Futuna Islands', 'Dependency', 'Overseas Collectivity', 'France', 'Mata\"utu', 'XPF', 'Franc', '681', 'WLF', '876', '.wf', 241, 0, 'wf.png', 0, NULL, NULL, 1, 1),
(240, 'WS', 'Samoa', 'Independent State of Samoa', 'Independent State', NULL, NULL, 'Apia', 'WST', 'Tala', '685', 'WSM', '882', '.ws', 190, 0, 'ws.png', 0, NULL, NULL, 1, 1),
(241, 'YE', 'Yemen', 'Republic of Yemen', 'Independent State', NULL, NULL, 'Sanaa', 'YER', 'Rial', '967', 'YEM', '887', '.ye', 243, 0, 'ye.png', 0, NULL, NULL, 1, 1),
(242, 'YT', 'Mayotte', 'Departmental Collectivity of Mayotte', 'Dependency', 'Overseas Collectivity', 'France', 'Mamoudzou', 'EUR', 'Euro', '262', 'MYT', '175', '.yt', 143, 0, 'yt.png', 0, NULL, NULL, 1, 1),
(243, 'ZA', 'South Africa', 'Republic of South Africa', 'Independent State', NULL, NULL, 'Pretoria (administrative), Cape Town (legislative), and Bloemfontein (judical)', 'ZAR', 'Rand', '27', 'ZAF', '710', '.za', 203, 0, 'za.png', 0, NULL, NULL, 1, 1),
(244, 'ZM', 'Zambia', 'Republic of Zambia', 'Independent State', NULL, NULL, 'Lusaka', 'ZMK', 'Kwacha', '260', 'ZMB', '894', '.zm', 244, 0, 'zm.png', 0, NULL, NULL, 1, 1),
(245, 'ZW', 'Zimbabwe', 'Republic of Zimbabwe', 'Independent State', NULL, NULL, 'Harare', 'ZWD', 'Dollar', '263', 'ZWE', '716', '.zw', 245, 0, 'zw.png', 0, NULL, NULL, 1, 1)");
        }
    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        echo "m200528_024126_create_table_location_country cannot be reverted.\n";

        return false;
    }

    /*
    // Use up()/down() to run migration code without a transaction.
    public function up()
    {

    }

    public function down()
    {
        echo "m200528_024126_create_table_location_country cannot be reverted.\n";

        return false;
    }
    */
}
