<?php
namespace modava\location\components;

use backend\components\MyController;

class MyLocationController extends MyController
{
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }
}
